name 'saz-dnsmasq'
version '1.0.2'

author 'saz'
license 'Apache License, Version 2.0'
project_page 'https://github.com/saz/puppet-dnsmasq'
source 'UNKNOWN'
summary 'UNKNOWN'
description 'Manage dnsmasq via Puppet'
dependency 'puppetlabs/stdlib', '>=2.0.0'
