# = Class: dnsmasq
#
# Installs and manages dnsmasq
#
# == Parameters
#
# [*upstream_servers*]
#   An array of upstream DNS servers to proxy.
#   Default: undef
#
# [*use_resolvconf*]
#   Boolean value to specify whether or not to use configuration
#   generated by resolvconf. Assumes that resolvconf will generate a
#   file in /var/run/dnsmasq/resolv.conf to be read by dnsmasq.
#   Default: no
class dnsmasq (
  $upstream_servers = undef,
  $use_resolvconf = 'no'
  ) {
  include dnsmasq::params

  anchor { 'dnsmasq::start': }

  class { 'dnsmasq::install':
    require => Anchor['dnsmasq::start'],
  }

  class { 'dnsmasq::config':
    upstream_servers => $upstream_servers,
    use_resolvconf   => $use_resolvconf,
    require          => Class['dnsmasq::install'],
  }

  class { 'dnsmasq::service':
    subscribe => Class[
      'dnsmasq::install',
      'dnsmasq::config'
    ],
  }

  class { 'dnsmasq::reload':
    require => Class['dnsmasq::service'],
  }

  anchor { 'dnsmasq::end':
    require => Class['dnsmasq::service'],
  }
}
